---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

node:
  runner: potato-core

steps:
- name: gut
  commands:
  - Godot_v3.1.1-stable_linux_headless.64 -s addons/gut/gut_cmdln.gd --no-window -d --path $PWD -gdir=res://unit_testing/Unit/ -gprefix=test -gexit
