---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

node:
  runner: potato-core-docker

steps:

- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive -j 8

- name: reimport
  image: godot
  pull: never
  commands:
  - mkdir builds
  - mkdir builds/linux
  - godot --export-debug "nil" --path . builds/linux/jogo_exportado_linux


- name: gut
  image: godot
  pull: never
  commands:
  - godot -s --path . addons/gut/gut_cmdln.gd -gdir=res://unit_testing/Unit/ -gprefix=test -gexit


